# Learn more: https://shopify.dev/docs/apps/tools/cli/configuration

name = "Juspit B2B Quote"
client_id = "YOUR_CLIENT_ID"
application_url = "https://YOUR_HOST"
embedded = false

[access_scopes]
scopes = "write_draft_orders,read_customers,read_products"

[auth]
redirect_urls = [
  "https://YOUR_HOST/auth/callback",
]

[webhooks]
api_version = "2025-01"

[app_proxy]
url = "https://YOUR_HOST/api/proxy"
subpath = "create-b2b-draft-order"
prefix = "apps"

[pos]
embedded = false
